# Generated by Django 2.0.7 on 2018-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anode',
            name='anode_value',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='snode',
            name='snode_value',
            field=models.IntegerField(default=None),
        ),
    ]
