# Generated by Django 2.0.7 on 2018-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0002_auto_20180808_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcginfo',
            name='cctv_num',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
