# Generated by Django 2.0.7 on 2018-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0003_gcginfo_cctv_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcg',
            name='anode_num',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcg',
            name='cctv_num',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcg',
            name='snode_num',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
