# Generated by Django 2.0.7 on 2018-08-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palm', '0004_auto_20180808_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcg',
            name='owner',
        ),
        migrations.AddField(
            model_name='gcg',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='gcg_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
