# Generated by Django 2.0.7 on 2018-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0006_auto_20180808_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anode',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
