# Generated by Django 2.0.7 on 2018-08-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0007_auto_20180808_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='cctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('gcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palm.Gcg')),
            ],
        ),
    ]
