# Generated by Django 2.0.7 on 2018-08-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0009_auto_20180809_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cctv_inside',
            new_name='CctvInside',
        ),
        migrations.RenameModel(
            old_name='cctv_outside',
            new_name='CctvOutside',
        ),
    ]
