# Generated by Django 2.0.7 on 2018-08-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0010_auto_20180809_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='gcg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='palm.Gcg'),
            preserve_default=False,
        ),
    ]
