# Generated by Django 2.0.7 on 2018-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0011_emergency_gcg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
