# Generated by Django 2.0.7 on 2018-08-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0014_testanode_testgcg_testsnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanode',
            name='gcg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palm.TestGcg'),
        ),
    ]
