# Generated by Django 2.0.7 on 2018-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0016_auto_20180823_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanode',
            name='anode_value',
        ),
        migrations.RemoveField(
            model_name='testsnode',
            name='snode_value',
        ),
        migrations.AddField(
            model_name='testanode',
            name='anode_value1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testsnode',
            name='snode_value_humd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testsnode',
            name='snode_value_temp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
