# Generated by Django 2.0.7 on 2018-08-23 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0018_test1_testn'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
