# Generated by Django 2.0.7 on 2018-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0019_test1_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsnode',
            name='data_display',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
