# Generated by Django 2.0.7 on 2018-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0020_testsnode_data_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsnode',
            name='data_display',
        ),
    ]
