# Generated by Django 2.0.7 on 2018-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0021_remove_testsnode_data_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanode',
            name='anode_value1',
        ),
        migrations.AddField(
            model_name='testanode',
            name='anode_value',
            field=models.BooleanField(default=False),
        ),
    ]
